# Generated by Django 4.2.7 on 2023-11-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_document_delete_docuemnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='qa_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
